export const GET_ERRORS = "GET_ERRORS";
export const SET_USER_LOGIN_STATUS = "SET_USER_LOGIN_STATUS";
export const SET_PROPRTY_SEARCH_DATA = "SET_PROPRTY_SEARCH_DATA";
export const GET_PROPERTY_ID = "GET_PROPERTY_ID";
export const POST_PROPERTY_DETAILS = "POST_PROPERTY_DETAILS";
export const CONFIRM_PROPERTY_DETAILS = "CONFIRM_PROPERTY_DETAILS";
export const CANCEL_PROPERTY_DETAILS = "CANCEL_PROPERTY_DETAILS";
